/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessControlHandlerConfig {
    #[serde(rename = "ignoreRelative", skip_serializing_if = "Option::is_none")]
    pub ignore_relative: Option<bool>,
    #[serde(rename = "pickRoleMembers", skip_serializing_if = "Option::is_none")]
    pub pick_role_members: Option<String>,
    #[serde(rename = "roleNames", skip_serializing_if = "Option::is_none")]
    pub role_names: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl AccessControlHandlerConfig {
    pub fn new(r#type: String) -> AccessControlHandlerConfig {
        AccessControlHandlerConfig {
            ignore_relative: None,
            pick_role_members: None,
            role_names: None,
            r#type,
        }
    }
}

