/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessControlConfig {
    #[serde(rename = "event_signature")]
    pub event_signature: String,
    #[serde(rename = "pick_role_members", skip_serializing_if = "Option::is_none")]
    pub pick_role_members: Option<String>,
    #[serde(rename = "role_names", skip_serializing_if = "Option::is_none")]
    pub role_names: Option<std::collections::HashMap<String, String>>,
}

impl AccessControlConfig {
    pub fn new(event_signature: String) -> AccessControlConfig {
        AccessControlConfig {
            event_signature,
            pick_role_members: None,
            role_names: None,
        }
    }
}

