/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyzeAbiRequest {
    #[serde(rename = "contract_info")]
    pub contract_info: models::ContractInfo,
    #[serde(rename = "intent", skip_serializing_if = "Option::is_none")]
    pub intent: Option<String>,
    #[serde(rename = "__baml_options__", skip_serializing_if = "Option::is_none")]
    pub __baml_options__: Option<models::BamlOptions>,
}

impl AnalyzeAbiRequest {
    pub fn new(contract_info: models::ContractInfo) -> AnalyzeAbiRequest {
        AnalyzeAbiRequest {
            contract_info,
            intent: None,
            __baml_options__: None,
        }
    }
}

