/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallableRetrieval {
    #[serde(rename = "function_signature")]
    pub function_signature: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "parameter_types", skip_serializing_if = "Option::is_none")]
    pub parameter_types: Option<Vec<String>>,
    #[serde(rename = "requires_parameters")]
    pub requires_parameters: bool,
    #[serde(rename = "return_type")]
    pub return_type: String,
}

impl CallableRetrieval {
    pub fn new(function_signature: String, name: String, requires_parameters: bool, return_type: String) -> CallableRetrieval {
        CallableRetrieval {
            function_signature,
            name,
            notes: None,
            parameter_types: None,
            requires_parameters,
            return_type,
        }
    }
}

