/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatMessage {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "role")]
    pub role: String,
}

impl ChatMessage {
    pub fn new(content: String, role: String) -> ChatMessage {
        ChatMessage {
            content,
            role,
        }
    }
}

