/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractAnalysis {
    #[serde(rename = "handlers")]
    pub handlers: Vec<models::FieldHandler>,
    #[serde(rename = "patternDetected", skip_serializing_if = "Option::is_none")]
    pub pattern_detected: Option<String>,
    #[serde(rename = "summary")]
    pub summary: String,
}

impl ContractAnalysis {
    pub fn new(handlers: Vec<models::FieldHandler>, summary: String) -> ContractAnalysis {
        ContractAnalysis {
            handlers,
            pattern_detected: None,
            summary,
        }
    }
}
