/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractInfo {
    #[serde(rename = "abi", skip_serializing_if = "Option::is_none")]
    pub abi: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "source_code", skip_serializing_if = "Option::is_none")]
    pub source_code: Option<String>,
}

impl ContractInfo {
    pub fn new() -> ContractInfo {
        ContractInfo {
            abi: None,
            address: None,
            description: None,
            source_code: None,
        }
    }
}
