/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationSummary {
    #[serde(rename = "current_state")]
    pub current_state: String,
    #[serde(rename = "key_details")]
    pub key_details: Vec<String>,
    #[serde(rename = "main_topic")]
    pub main_topic: String,
    #[serde(rename = "user_friendly_summary")]
    pub user_friendly_summary: String,
}

impl ConversationSummary {
    pub fn new(
        current_state: String,
        key_details: Vec<String>,
        main_topic: String,
        user_friendly_summary: String,
    ) -> ConversationSummary {
        ConversationSummary {
            current_state,
            key_details,
            main_topic,
            user_friendly_summary,
        }
    }
}
