/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DynamicArrayHandlerConfig {
    #[serde(rename = "ignoreRelative", skip_serializing_if = "Option::is_none")]
    pub ignore_relative: Option<bool>,
    #[serde(rename = "returnType", skip_serializing_if = "Option::is_none")]
    pub return_type: Option<String>,
    #[serde(rename = "slot")]
    pub slot: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl DynamicArrayHandlerConfig {
    pub fn new(slot: String, r#type: String) -> DynamicArrayHandlerConfig {
        DynamicArrayHandlerConfig {
            ignore_relative: None,
            return_type: None,
            slot,
            r#type,
        }
    }
}
