/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventAction {
    #[serde(rename = "action_description")]
    pub action_description: String,
    #[serde(rename = "field_name")]
    pub field_name: String,
    #[serde(rename = "handler")]
    pub handler: models::EventActionHandler,
}

impl EventAction {
    pub fn new(action_description: String, field_name: String, handler: models::EventActionHandler) -> EventAction {
        EventAction {
            action_description,
            field_name,
            handler,
        }
    }
}

