/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EventActionHandler {
    EventHandlerConfig(models::EventHandlerConfig),
    AccessControlConfig(models::AccessControlConfig),
}

impl Default for EventActionHandler {
    fn default() -> Self {
        Self::EventHandlerConfig(Default::default())
    }
}

