/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventHandlerConfig {
    #[serde(rename = "add", skip_serializing_if = "Option::is_none")]
    pub add: Option<models::EventOperation>,
    #[serde(rename = "event_signature", skip_serializing_if = "Option::is_none")]
    pub event_signature: Option<String>,
    #[serde(rename = "remove", skip_serializing_if = "Option::is_none")]
    pub remove: Option<models::EventOperation>,
    #[serde(rename = "return_type")]
    pub return_type: String,
    #[serde(rename = "select_field")]
    pub select_field: String,
}

impl EventHandlerConfig {
    pub fn new(return_type: String, select_field: String) -> EventHandlerConfig {
        EventHandlerConfig {
            add: None,
            event_signature: None,
            remove: None,
            return_type,
            select_field,
        }
    }
}
