/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventInfo {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "event_signature")]
    pub event_signature: String,
    #[serde(rename = "query_fields")]
    pub query_fields: Vec<String>,
}

impl EventInfo {
    pub fn new(
        description: String,
        event_signature: String,
        query_fields: Vec<String>,
    ) -> EventInfo {
        EventInfo {
            description,
            event_signature,
            query_fields,
        }
    }
}
