/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventOperation {
    #[serde(rename = "event_signature")]
    pub event_signature: String,
    #[serde(rename = "where", skip_serializing_if = "Option::is_none")]
    pub r#where: Option<Vec<String>>,
}

impl EventOperation {
    pub fn new(event_signature: String) -> EventOperation {
        EventOperation {
            event_signature,
            r#where: None,
        }
    }
}

