/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldHandler {
    #[serde(rename = "config")]
    pub config: models::FieldHandlerConfig,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "fieldName")]
    pub field_name: String,
}

impl FieldHandler {
    pub fn new(config: models::FieldHandlerConfig, field_name: String) -> FieldHandler {
        FieldHandler {
            config,
            description: None,
            field_name,
        }
    }
}

