/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateForgeScriptRequest {
    #[serde(rename = "contract_context")]
    pub contract_context: models::ContractInfo,
    #[serde(rename = "user_intent")]
    pub user_intent: String,
    #[serde(rename = "__baml_options__", skip_serializing_if = "Option::is_none")]
    pub __baml_options__: Option<models::BamlOptions>,
}

impl GenerateForgeScriptRequest {
    pub fn new(
        contract_context: models::ContractInfo,
        user_intent: String,
    ) -> GenerateForgeScriptRequest {
        GenerateForgeScriptRequest {
            contract_context,
            user_intent,
            __baml_options__: None,
        }
    }
}
