/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateTransactionCallsRequest {
    #[serde(rename = "available_interfaces")]
    pub available_interfaces: Vec<models::InterfaceDefinition>,
    #[serde(rename = "deployed_addresses")]
    pub deployed_addresses: std::collections::HashMap<String, String>,
    #[serde(rename = "operations")]
    pub operations: Vec<models::Operation>,
    #[serde(rename = "__baml_options__", skip_serializing_if = "Option::is_none")]
    pub __baml_options__: Option<models::BamlOptions>,
}

impl GenerateTransactionCallsRequest {
    pub fn new(available_interfaces: Vec<models::InterfaceDefinition>, deployed_addresses: std::collections::HashMap<String, String>, operations: Vec<models::Operation>) -> GenerateTransactionCallsRequest {
        GenerateTransactionCallsRequest {
            available_interfaces,
            deployed_addresses,
            operations,
            __baml_options__: None,
        }
    }
}

