/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeneratedScript {
    #[serde(rename = "interfaces_needed")]
    pub interfaces_needed: Vec<models::InterfaceDefinition>,
    #[serde(rename = "transaction_calls")]
    pub transaction_calls: Vec<models::TransactionCall>,
}

impl GeneratedScript {
    pub fn new(interfaces_needed: Vec<models::InterfaceDefinition>, transaction_calls: Vec<models::TransactionCall>) -> GeneratedScript {
        GeneratedScript {
            interfaces_needed,
            transaction_calls,
        }
    }
}

