/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Source of the interface definition
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InterfaceSource {
    #[serde(rename = "ForgeStd")]
    ForgeStd,
    #[serde(rename = "Inline")]
    Inline,
}

impl std::fmt::Display for InterfaceSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ForgeStd => write!(f, "ForgeStd"),
            Self::Inline => write!(f, "Inline"),
        }
    }
}

impl Default for InterfaceSource {
    fn default() -> InterfaceSource {
        Self::ForgeStd
    }
}
