/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Resume {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "experience")]
    pub experience: Vec<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "skills")]
    pub skills: Vec<String>,
}

impl Resume {
    pub fn new(email: String, experience: Vec<String>, name: String, skills: Vec<String>) -> Resume {
        Resume {
            email,
            experience,
            name,
            skills,
        }
    }
}

