/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionTitle {
    #[serde(rename = "title")]
    pub title: String,
}

impl SessionTitle {
    pub fn new(title: String) -> SessionTitle {
        SessionTitle { title }
    }
}
