/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlotInfo {
    #[serde(rename = "base_slot", skip_serializing_if = "Option::is_none")]
    pub base_slot: Option<String>,
    #[serde(rename = "getter_signature", skip_serializing_if = "Option::is_none")]
    pub getter_signature: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl SlotInfo {
    pub fn new(name: String, r#type: String) -> SlotInfo {
        SlotInfo {
            base_slot: None,
            getter_signature: None,
            name,
            notes: None,
            offset: None,
            r#type,
        }
    }
}

