/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageParam {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slot")]
    pub slot: String,
}

impl StorageParam {
    pub fn new(address: String, name: String, slot: String) -> StorageParam {
        StorageParam {
            address,
            name,
            slot,
        }
    }
}
