// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated enum types.

use baml::{BamlEncode, BamlDecode};



#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode)]
pub enum InterfaceSource {


    ForgeStd,


    Inline,

}

impl AsRef<InterfaceSource> for InterfaceSource {
    fn as_ref(&self) -> &InterfaceSource {
        self
    }
}

