// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod unions;
mod type_aliases;

pub use classes::*;
pub use enums::*;
pub use unions::*;
pub use type_aliases::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone)]
pub enum Types {

    ABIAnalysisResult(ABIAnalysisResult),

    AccessControlConfig(AccessControlConfig),

    AccessControlHandlerConfig(AccessControlHandlerConfig),

    CallHandlerConfig(CallHandlerConfig),

    CallableRetrieval(CallableRetrieval),

    ChatMessage(ChatMessage),

    CodeLine(CodeLine),

    ContractAnalysis(ContractAnalysis),

    ContractInfo(ContractInfo),

    ConversationSummary(ConversationSummary),

    DynamicArrayHandlerConfig(DynamicArrayHandlerConfig),

    Event(Event),

    EventAction(EventAction),

    EventAnalyzeResult(EventAnalyzeResult),

    EventHandlerConfig(EventHandlerConfig),

    EventInfo(EventInfo),

    EventOperation(EventOperation),

    ExtractedContractInfo(ExtractedContractInfo),

    FieldHandler(FieldHandler),

    Function(Function),

    FunctionSignature(FunctionSignature),

    GeneratedScript(GeneratedScript),

    Import(Import),

    Interface(Interface),

    InterfaceDefinition(InterfaceDefinition),

    LayoutAnalysisResult(LayoutAnalysisResult),

    Operation(Operation),

    Parameter(Parameter),

    Resume(Resume),

    ScriptBlock(ScriptBlock),

    SessionTitle(SessionTitle),

    SlotInfo(SlotInfo),

    Storage(Storage),

    StorageHandlerConfig(StorageHandlerConfig),

    TransactionCall(TransactionCall),


    InterfaceSource(InterfaceSource),


    Union2AccessControlConfigOrEventHandlerConfig(Union2AccessControlConfigOrEventHandlerConfig),

    Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig(Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig),

}

impl baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            Types::ABIAnalysisResult(_) => "ABIAnalysisResult",

            Types::AccessControlConfig(_) => "AccessControlConfig",

            Types::AccessControlHandlerConfig(_) => "AccessControlHandlerConfig",

            Types::CallHandlerConfig(_) => "CallHandlerConfig",

            Types::CallableRetrieval(_) => "CallableRetrieval",

            Types::ChatMessage(_) => "ChatMessage",

            Types::CodeLine(_) => "CodeLine",

            Types::ContractAnalysis(_) => "ContractAnalysis",

            Types::ContractInfo(_) => "ContractInfo",

            Types::ConversationSummary(_) => "ConversationSummary",

            Types::DynamicArrayHandlerConfig(_) => "DynamicArrayHandlerConfig",

            Types::Event(_) => "Event",

            Types::EventAction(_) => "EventAction",

            Types::EventAnalyzeResult(_) => "EventAnalyzeResult",

            Types::EventHandlerConfig(_) => "EventHandlerConfig",

            Types::EventInfo(_) => "EventInfo",

            Types::EventOperation(_) => "EventOperation",

            Types::ExtractedContractInfo(_) => "ExtractedContractInfo",

            Types::FieldHandler(_) => "FieldHandler",

            Types::Function(_) => "Function",

            Types::FunctionSignature(_) => "FunctionSignature",

            Types::GeneratedScript(_) => "GeneratedScript",

            Types::Import(_) => "Import",

            Types::Interface(_) => "Interface",

            Types::InterfaceDefinition(_) => "InterfaceDefinition",

            Types::LayoutAnalysisResult(_) => "LayoutAnalysisResult",

            Types::Operation(_) => "Operation",

            Types::Parameter(_) => "Parameter",

            Types::Resume(_) => "Resume",

            Types::ScriptBlock(_) => "ScriptBlock",

            Types::SessionTitle(_) => "SessionTitle",

            Types::SlotInfo(_) => "SlotInfo",

            Types::Storage(_) => "Storage",

            Types::StorageHandlerConfig(_) => "StorageHandlerConfig",

            Types::TransactionCall(_) => "TransactionCall",


            Types::InterfaceSource(_) => "InterfaceSource",


            Types::Union2AccessControlConfigOrEventHandlerConfig(_) => "Union2AccessControlConfigOrEventHandlerConfig",

            Types::Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig(_) => "Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig",


        }
    }
}