// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod type_aliases;
mod unions;

pub use classes::*;
pub use type_aliases::*;
pub use unions::*;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone)]
pub enum StreamTypes {
    ABIAnalysisResult(ABIAnalysisResult),

    AccessControlConfig(AccessControlConfig),

    AccessControlHandlerConfig(AccessControlHandlerConfig),

    CallHandlerConfig(CallHandlerConfig),

    CallableRetrieval(CallableRetrieval),

    ChatMessage(ChatMessage),

    CodeLine(CodeLine),

    ContractAnalysis(ContractAnalysis),

    ContractInfo(ContractInfo),

    ConversationSummary(ConversationSummary),

    DynamicArrayHandlerConfig(DynamicArrayHandlerConfig),

    Event(Event),

    EventAction(EventAction),

    EventAnalyzeResult(EventAnalyzeResult),

    EventHandlerConfig(EventHandlerConfig),

    EventInfo(EventInfo),

    EventOperation(EventOperation),

    ExtractedContractInfo(ExtractedContractInfo),

    FieldHandler(FieldHandler),

    Function(Function),

    FunctionSignature(FunctionSignature),

    GeneratedScript(GeneratedScript),

    Import(Import),

    Interface(Interface),

    InterfaceDefinition(InterfaceDefinition),

    LayoutAnalysisResult(LayoutAnalysisResult),

    Operation(Operation),

    Parameter(Parameter),

    Resume(Resume),

    ScriptBlock(ScriptBlock),

    SessionTitle(SessionTitle),

    SlotInfo(SlotInfo),

    Storage(Storage),

    StorageHandlerConfig(StorageHandlerConfig),

    TransactionCall(TransactionCall),


    Union2AccessControlConfigOrEventHandlerConfig(Union2AccessControlConfigOrEventHandlerConfig),

    Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig(Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig),

}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            StreamTypes::ABIAnalysisResult(_) => "ABIAnalysisResult",

            StreamTypes::AccessControlConfig(_) => "AccessControlConfig",

            StreamTypes::AccessControlHandlerConfig(_) => "AccessControlHandlerConfig",

            StreamTypes::CallHandlerConfig(_) => "CallHandlerConfig",

            StreamTypes::CallableRetrieval(_) => "CallableRetrieval",

            StreamTypes::ChatMessage(_) => "ChatMessage",

            StreamTypes::CodeLine(_) => "CodeLine",

            StreamTypes::ContractAnalysis(_) => "ContractAnalysis",

            StreamTypes::ContractInfo(_) => "ContractInfo",

            StreamTypes::ConversationSummary(_) => "ConversationSummary",

            StreamTypes::DynamicArrayHandlerConfig(_) => "DynamicArrayHandlerConfig",

            StreamTypes::Event(_) => "Event",

            StreamTypes::EventAction(_) => "EventAction",

            StreamTypes::EventAnalyzeResult(_) => "EventAnalyzeResult",

            StreamTypes::EventHandlerConfig(_) => "EventHandlerConfig",

            StreamTypes::EventInfo(_) => "EventInfo",

            StreamTypes::EventOperation(_) => "EventOperation",

            StreamTypes::ExtractedContractInfo(_) => "ExtractedContractInfo",

            StreamTypes::FieldHandler(_) => "FieldHandler",

            StreamTypes::Function(_) => "Function",

            StreamTypes::FunctionSignature(_) => "FunctionSignature",

            StreamTypes::GeneratedScript(_) => "GeneratedScript",

            StreamTypes::Import(_) => "Import",

            StreamTypes::Interface(_) => "Interface",

            StreamTypes::InterfaceDefinition(_) => "InterfaceDefinition",

            StreamTypes::LayoutAnalysisResult(_) => "LayoutAnalysisResult",

            StreamTypes::Operation(_) => "Operation",

            StreamTypes::Parameter(_) => "Parameter",

            StreamTypes::Resume(_) => "Resume",

            StreamTypes::ScriptBlock(_) => "ScriptBlock",

            StreamTypes::SessionTitle(_) => "SessionTitle",

            StreamTypes::SlotInfo(_) => "SlotInfo",

            StreamTypes::Storage(_) => "Storage",

            StreamTypes::StorageHandlerConfig(_) => "StorageHandlerConfig",

            StreamTypes::TransactionCall(_) => "TransactionCall",


            StreamTypes::Union2AccessControlConfigOrEventHandlerConfig(_) => "Union2AccessControlConfigOrEventHandlerConfig",

            StreamTypes::Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig(_) => "Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig",


        }
    }
}
