// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated streaming union types.

use baml::BamlDecode;
use crate::baml_client::types;
use super::*;


/// Generated from: (Streaming.EventHandlerConfig | Streaming.AccessControlConfig | null)
#[derive(Debug, Clone, BamlDecode)]
#[baml(union)]
pub enum Union2AccessControlConfigOrEventHandlerConfig {

    #[baml(name = "EventHandlerConfig")]
    EventHandlerConfig(EventHandlerConfig),

    #[baml(name = "AccessControlConfig")]
    AccessControlConfig(AccessControlConfig),

}

impl AsRef<Union2AccessControlConfigOrEventHandlerConfig> for Union2AccessControlConfigOrEventHandlerConfig {
    fn as_ref(&self) -> &Union2AccessControlConfigOrEventHandlerConfig {
        self
    }
}

impl Default for Union2AccessControlConfigOrEventHandlerConfig {
    fn default() -> Self {
        
            Self::EventHandlerConfig(Default::default())
        
    }
}


/// Generated from: (Streaming.CallHandlerConfig | Streaming.StorageHandlerConfig | Streaming.EventHandlerConfig | Streaming.AccessControlHandlerConfig | Streaming.DynamicArrayHandlerConfig | null)
#[derive(Debug, Clone, BamlDecode)]
#[baml(union)]
pub enum Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig {

    #[baml(name = "CallHandlerConfig")]
    CallHandlerConfig(CallHandlerConfig),

    #[baml(name = "StorageHandlerConfig")]
    StorageHandlerConfig(StorageHandlerConfig),

    #[baml(name = "EventHandlerConfig")]
    EventHandlerConfig(EventHandlerConfig),

    #[baml(name = "AccessControlHandlerConfig")]
    AccessControlHandlerConfig(AccessControlHandlerConfig),

    #[baml(name = "DynamicArrayHandlerConfig")]
    DynamicArrayHandlerConfig(DynamicArrayHandlerConfig),

}

impl AsRef<Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig> for Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig {
    fn as_ref(&self) -> &Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig {
        self
    }
}

impl Default for Union5AccessControlHandlerConfigOrCallHandlerConfigOrDynamicArrayHandlerConfigOrEventHandlerConfigOrStorageHandlerConfig {
    fn default() -> Self {
        
            Self::CallHandlerConfig(Default::default())
        
    }
}

