[package]
name = "aomi-terminal"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
baml-client = { path = "./baml_client" }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true