/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FieldHandlerConfig {
    CallHandlerConfig(models::CallHandlerConfig),
    StorageHandlerConfig(models::StorageHandlerConfig),
    EventHandlerConfig(models::EventHandlerConfig),
    AccessControlHandlerConfig(models::AccessControlHandlerConfig),
    DynamicArrayHandlerConfig(models::DynamicArrayHandlerConfig),
}

impl Default for FieldHandlerConfig {
    fn default() -> Self {
        Self::CallHandlerConfig(Default::default())
    }
}
