services:
  backend:
    image: ghcr.io/aomi-labs/product-mono/backend:deployment-ver2
    env_file:
      - .env.prod
    environment:
      # inbound mcp:5001 <- 0.0.0.0:8081 from mcp service
      MCP_SERVER_HOST: mcp
      MCP_SERVER_PORT: 5001
      # outbound 0.0.0.0:8081 -> backend:8081
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 8081
      BACKEND_SKIP_DOCS: true
      RUST_LOG: info
    ports:
      - "8081:8081"
    depends_on:
      - mcp
    restart: unless-stopped

  mcp:
    image: ghcr.io/aomi-labs/product-mono/mcp:deployment-ver2
    env_file:
      - .env.prod
    environment:
      # outbound 0.0.0.0:8081 -> mcp:5001
      MCP_SERVER_HOST: 0.0.0.0
      MCP_SERVER_PORT: 5001
      RUST_LOG: info
    ports:
      - "5001:5001"
    depends_on:
      - anvil
    restart: unless-stopped

  frontend:
    image: ghcr.io/aomi-labs/product-mono/frontend:deployment-ver2
    env_file:
      - .env.prod
    environment:
      ########
      # DOT SET BACKEND_URL AND ANVIL_URL, Next.js env is compiled at built time
      # and a production websit will have to visti http://aomi.dev:8081 and http://adomi.dev:8545
      ########
      PORT: 3001
    ports:
      - "80:3001"
    depends_on:
      - backend
    restart: unless-stopped

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: []
    command:
      - anvil
      - --host
      - 0.0.0.0
      - --fork-url
      - https://eth-mainnet.public.blastapi.io
    ports:
      - "8545:8545"
    restart: unless-stopped
