services:
  backend:
    build:
      context: .
      target: backend-runtime
    image: forge-mcp-backend:latest
    env_file:
      - .env.prod
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-0.0.0.0}
      BACKEND_PORT: ${BACKEND_PORT:-8081}
      BACKEND_SKIP_DOCS: ${BACKEND_SKIP_DOCS:-false}
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "${BACKEND_PORT:-8081}:${BACKEND_PORT:-8081}"
    depends_on:
      - mcp
    restart: unless-stopped

  mcp:
    build:
      context: .
      target: mcp-runtime
    image: forge-mcp-mcp:latest
    env_file:
      - .env.prod
    environment:
      MCP_SERVER_HOST: ${MCP_SERVER_HOST:-0.0.0.0}
      MCP_SERVER_PORT: ${MCP_SERVER_PORT:-5001}
      RUST_LOG: ${MCP_RUST_LOG:-info}
    ports:
      - "${MCP_SERVER_PORT:-5001}:${MCP_SERVER_PORT:-5001}"
    depends_on:
      - anvil
    restart: unless-stopped

  frontend:
    build:
      context: .
      target: frontend-runtime
    image: forge-mcp-frontend:latest
    env_file:
      - .env.prod
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8081}
      PORT: ${FRONTEND_PORT:-3001}
    ports:
      - "${FRONTEND_PORT:-3001}:${FRONTEND_PORT:-3001}"
    depends_on:
      - backend
    restart: unless-stopped

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command:
      - anvil
      - --host
      - 0.0.0.0
      - --fork-url
      - ${ETH_RPC_URL:-https://eth-mainnet.public.blastapi.io}
    ports:
      - "8545:8545"
    restart: unless-stopped
