version: '3.8'

services:
  # Anvil Ethereum simulator
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: ["anvil", "--host", "0.0.0.0", "--fork-url", "https://eth-mainnet.public.blastapi.io@22419684"]
    ports:
      - "8545:8545"
    networks:
      - forge-mcp

  # Main forge-mcp application stack
  forge-mcp:
    build: .
    environment:
      - FORGE_ENV=production
      - RUST_LOG=warn
      - NODE_ENV=production
    env_file:
      - .env.prod
    ports:
      - "5001:5001"  # MCP Server
      - "8081:8081"  # Backend API
      - "3001:3001"  # Frontend
    depends_on:
      - anvil
    networks:
      - forge-mcp
    volumes:
      - ./documents:/home/forge-mcp/documents:ro
    restart: unless-stopped

  # Optional: Reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - forge-mcp
    networks:
      - forge-mcp
    restart: unless-stopped
    profiles:
      - production

networks:
  forge-mcp:
    driver: bridge

volumes:
  forge-mcp-data: