services:
  backend:
    build:
      context: .
      target: backend-runtime
    env_file:
      - .env.dev
    environment:
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: ${BACKEND_PORT:-8080}
      BACKEND_SKIP_DOCS: ${BACKEND_SKIP_DOCS:-true}
      RUST_LOG: ${RUST_LOG:-debug}
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    depends_on:
      - mcp
    restart: unless-stopped

  mcp:
    build:
      context: .
      target: mcp-runtime
    env_file:
      - .env.dev
    environment:
      MCP_SERVER_HOST: 0.0.0.0
      MCP_SERVER_PORT: ${MCP_SERVER_PORT:-5000}
      MCP_NETWORK_URLS_JSON: ${MCP_NETWORK_URLS_JSON:-}
      RUST_LOG: ${MCP_RUST_LOG:-debug}
    ports:
      - "${MCP_SERVER_PORT:-5000}:${MCP_SERVER_PORT:-5000}"
    restart: unless-stopped

  frontend:
    build:
      context: .
      target: frontend-runtime
    env_file:
      - .env.dev
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8080}
      PORT: ${FRONTEND_PORT:-3000}
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    depends_on:
      - backend
    restart: unless-stopped

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command:
      - anvil
      - --host
      - 0.0.0.0
      - --fork-url
      - ${ETH_RPC_URL:-https://eth-mainnet.g.alchemy.com/v2/demo}
    ports:
      - "8545:8545"
    restart: unless-stopped
