/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyzeLayoutRequest {
    #[serde(rename = "abi_result")]
    pub abi_result: models::AbiAnalysisResult,
    #[serde(rename = "contract_info")]
    pub contract_info: models::ContractInfo,
    #[serde(rename = "intent")]
    pub intent: String,
    #[serde(rename = "__baml_options__", skip_serializing_if = "Option::is_none")]
    pub __baml_options__: Option<models::BamlOptions>,
}

impl AnalyzeLayoutRequest {
    pub fn new(
        abi_result: models::AbiAnalysisResult,
        contract_info: models::ContractInfo,
        intent: String,
    ) -> AnalyzeLayoutRequest {
        AnalyzeLayoutRequest {
            abi_result,
            contract_info,
            intent,
            __baml_options__: None,
        }
    }
}
