/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyzeContractForHandlersRequest {
    #[serde(rename = "contract_info")]
    pub contract_info: models::ContractInfo,
    #[serde(rename = "intent")]
    pub intent: String,
    #[serde(rename = "__baml_options__", skip_serializing_if = "Option::is_none")]
    pub __baml_options__: Option<models::BamlOptions>,
}

impl AnalyzeContractForHandlersRequest {
    pub fn new(contract_info: models::ContractInfo, intent: String) -> AnalyzeContractForHandlersRequest {
        AnalyzeContractForHandlersRequest {
            contract_info,
            intent,
            __baml_options__: None,
        }
    }
}

