/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallHandlerConfig {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<String>>,
    #[serde(rename = "expectRevert", skip_serializing_if = "Option::is_none")]
    pub expect_revert: Option<bool>,
    #[serde(rename = "ignoreRelative", skip_serializing_if = "Option::is_none")]
    pub ignore_relative: Option<bool>,
    #[serde(rename = "method")]
    pub method: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CallHandlerConfig {
    pub fn new(method: String, r#type: String) -> CallHandlerConfig {
        CallHandlerConfig {
            address: None,
            args: None,
            expect_revert: None,
            ignore_relative: None,
            method,
            r#type,
        }
    }
}
