/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeLine {
    #[serde(rename = "import_spec", skip_serializing_if = "Option::is_none")]
    pub import_spec: Option<models::Import>,
    #[serde(rename = "interface", skip_serializing_if = "Option::is_none")]
    pub interface: Option<models::Interface>,
    #[serde(rename = "line")]
    pub line: String,
}

impl CodeLine {
    pub fn new(line: String) -> CodeLine {
        CodeLine {
            import_spec: None,
            interface: None,
            line,
        }
    }
}
