/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractInfo {
    #[serde(rename = "abi")]
    pub abi: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "source_code", skip_serializing_if = "Option::is_none")]
    pub source_code: Option<String>,
}

impl ContractInfo {
    pub fn new(abi: String, address: String) -> ContractInfo {
        ContractInfo {
            abi,
            address,
            description: None,
            source_code: None,
        }
    }
}

