/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "abi")]
    pub abi: String,
    #[serde(rename = "signature")]
    pub signature: String,
}

impl Event {
    pub fn new(abi: String, signature: String) -> Event {
        Event {
            abi,
            signature,
        }
    }
}

