/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtractedContractInfo {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "events")]
    pub events: Vec<models::Event>,
    #[serde(rename = "functions")]
    pub functions: Vec<models::Function>,
    #[serde(rename = "interface_name")]
    pub interface_name: String,
    #[serde(rename = "storages")]
    pub storages: Vec<models::Storage>,
}

impl ExtractedContractInfo {
    pub fn new(address: String, events: Vec<models::Event>, functions: Vec<models::Function>, interface_name: String, storages: Vec<models::Storage>) -> ExtractedContractInfo {
        ExtractedContractInfo {
            address,
            description: None,
            events,
            functions,
            interface_name,
            storages,
        }
    }
}

