/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtractResumeRequest {
    #[serde(rename = "resume")]
    pub resume: String,
    #[serde(rename = "__baml_options__", skip_serializing_if = "Option::is_none")]
    pub __baml_options__: Option<models::BamlOptions>,
}

impl ExtractResumeRequest {
    pub fn new(resume: String) -> ExtractResumeRequest {
        ExtractResumeRequest {
            resume,
            __baml_options__: None,
        }
    }
}
