/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtractContractInfoRequest {
    #[serde(rename = "contracts")]
    pub contracts: Vec<models::ContractInfo>,
    #[serde(rename = "group_operations")]
    pub group_operations: Vec<String>,
    #[serde(rename = "__baml_options__", skip_serializing_if = "Option::is_none")]
    pub __baml_options__: Option<models::BamlOptions>,
}

impl ExtractContractInfoRequest {
    pub fn new(
        contracts: Vec<models::ContractInfo>,
        group_operations: Vec<String>,
    ) -> ExtractContractInfoRequest {
        ExtractContractInfoRequest {
            contracts,
            group_operations,
            __baml_options__: None,
        }
    }
}
