/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionSignature {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "signature")]
    pub signature: String,
}

impl FunctionSignature {
    pub fn new(name: String, signature: String) -> FunctionSignature {
        FunctionSignature { name, signature }
    }
}
