/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateScriptRequest {
    #[serde(rename = "extracted_infos")]
    pub extracted_infos: Vec<models::ExtractedContractInfo>,
    #[serde(rename = "group_operations")]
    pub group_operations: Vec<String>,
    #[serde(rename = "__baml_options__", skip_serializing_if = "Option::is_none")]
    pub __baml_options__: Option<models::BamlOptions>,
}

impl GenerateScriptRequest {
    pub fn new(extracted_infos: Vec<models::ExtractedContractInfo>, group_operations: Vec<String>) -> GenerateScriptRequest {
        GenerateScriptRequest {
            extracted_infos,
            group_operations,
            __baml_options__: None,
        }
    }
}

