/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Interface {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "solidity_code")]
    pub solidity_code: String,
}

impl Interface {
    pub fn new(name: String, solidity_code: String) -> Interface {
        Interface {
            name,
            solidity_code,
        }
    }
}

