/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterfaceDefinition {
    #[serde(rename = "functions")]
    pub functions: Vec<models::FunctionSignature>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "solidity_code", skip_serializing_if = "Option::is_none")]
    pub solidity_code: Option<String>,
    #[serde(rename = "source")]
    pub source: models::InterfaceSource,
}

impl InterfaceDefinition {
    pub fn new(
        functions: Vec<models::FunctionSignature>,
        name: String,
        source: models::InterfaceSource,
    ) -> InterfaceDefinition {
        InterfaceDefinition {
            functions,
            name,
            solidity_code: None,
            source,
        }
    }
}
