/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Operation {
    #[serde(rename = "abi")]
    pub abi: String,
    #[serde(rename = "contract_address")]
    pub contract_address: String,
    #[serde(rename = "contract_name", skip_serializing_if = "Option::is_none")]
    pub contract_name: Option<String>,
    #[serde(rename = "eth_value", skip_serializing_if = "Option::is_none")]
    pub eth_value: Option<String>,
    #[serde(rename = "function_name")]
    pub function_name: String,
    #[serde(rename = "parameters")]
    pub parameters: Vec<models::Parameter>,
}

impl Operation {
    pub fn new(
        abi: String,
        contract_address: String,
        function_name: String,
        parameters: Vec<models::Parameter>,
    ) -> Operation {
        Operation {
            abi,
            contract_address,
            contract_name: None,
            eth_value: None,
            function_name,
            parameters,
        }
    }
}
