/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Parameter {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "param_type")]
    pub param_type: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl Parameter {
    pub fn new(name: String, param_type: String, value: String) -> Parameter {
        Parameter {
            name,
            param_type,
            value,
        }
    }
}

