/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScriptBlock {
    #[serde(rename = "codelines")]
    pub codelines: Vec<models::CodeLine>,
}

impl ScriptBlock {
    pub fn new(codelines: Vec<models::CodeLine>) -> ScriptBlock {
        ScriptBlock {
            codelines,
        }
    }
}

