/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionCall {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "solidity_code")]
    pub solidity_code: String,
}

impl TransactionCall {
    pub fn new(description: String, solidity_code: String) -> TransactionCall {
        TransactionCall {
            description,
            solidity_code,
        }
    }
}
