// BAML client module for Forge script generation
//
// This module provides a two-phase interface for generating Forge scripts:
// 1. Phase 1: Extract relevant contract information from full ABIs and source code
// 2. Phase 2: Generate Solidity script code with import/interface decisions
//
// The generated BAML client is in the separate `baml-client` crate located at
// `aomi/crates/tools/src/baml/baml_client/`

// Use the forge-baml-client crate (generated by BAML)
use forge_baml_client as baml_client;

pub mod client;
pub mod types;

// Re-export main types for convenience
pub use client::BamlClient;
pub use types::{
    CodeLine, ContractInfo, ContractSource, Event, ExtractedContractInfo, Function,
    GenerateScriptRequest, Import, Interface, ScriptBlock, Storage,
};
