/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Import {
    #[serde(rename = "interface_name")]
    pub interface_name: String,
    #[serde(rename = "source")]
    pub source: String,
}

impl Import {
    pub fn new(interface_name: String, source: String) -> Import {
        Import {
            interface_name,
            source,
        }
    }
}
