// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Synchronous BAML client with function-object pattern.

use crate::baml_client::{runtime::{get_runtime, FunctionOptions}, stream_types, types};
use baml::{BamlEncode, BamlError, StreamingCall};

// =============================================================================
// Convenience Builder Methods Macro
// =============================================================================

/// Implements convenience builder methods that delegate to `with_options`.
/// Requires the type to have:
/// - `options: FunctionOptions` field
/// - `fn with_options(&self, options: FunctionOptions) -> Self` method
macro_rules! impl_options_convenience_methods {
    ($name:ident) => {
        impl $name {
            pub fn with_collector(&self, collector: &baml::Collector) -> Self {
                self.with_options(self.options.clone().with_collector(collector))
            }

            pub fn with_type_builder(&self, tb: &super::super::type_builder::TypeBuilder) -> Self {
                self.with_options(self.options.clone().with_type_builder(tb))
            }

            pub fn with_env_var(&self, key: impl Into<String>, value: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_env_var(key, value))
            }

            pub fn with_tag(&self, key: impl Into<String>, value: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_tag(key, value))
            }

            pub fn with_client(&self, client_name: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_client(client_name))
            }

            pub fn with_client_registry(&self, registry: &baml::ClientRegistry) -> Self {
                self.with_options(self.options.clone().with_client_registry(registry))
            }
        }
    };
}

// =============================================================================
// Function Struct Macro (generates per-function struct)
// =============================================================================

macro_rules! baml_function_sync {
    ($name:ident($($param:ident : $ptype:ty),* $(,)?) -> ($stream_ret:ty, $final_ret:ty)) => {
        #[derive(Clone)]
        pub struct $name {
            pub(crate) options: FunctionOptions,
        }

        impl $name {
            pub const fn new() -> Self {
                Self { options: FunctionOptions::new() }
            }

            fn with_options(&self, options: FunctionOptions) -> Self {
                Self { options }
            }

            // Terminal methods
            pub fn call(&self, $($param: $ptype),*) -> Result<$final_ret, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*;
                get_runtime().call_function(stringify!($name), &args)
            }

            pub fn stream(&self, $($param: $ptype),*) -> Result<StreamingCall<$stream_ret, $final_ret>, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*;
                get_runtime().call_function_stream(stringify!($name), &args)
            }

            pub fn parse(&self, response: &str) -> Result<$final_ret, BamlError> {
                // TODO: Implement parse via runtime
                todo!("parse not yet implemented")
            }

            pub fn parse_stream(&self, response: &str) -> Result<$stream_ret, BamlError> {
                // TODO: Implement parse_stream via runtime
                todo!("parse_stream not yet implemented")
            }
        }

        // Builder convenience methods (separate impl block via macro)
        impl_options_convenience_methods!($name);
    };
}

// =============================================================================
// Generate function structs
// =============================================================================



baml_function_sync!(AnalyzeABI(contract_info: &types::ContractInfo, intent: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::ABIAnalysisResult, types::ABIAnalysisResult));


baml_function_sync!(AnalyzeContractForHandlers(contract_info: &types::ContractInfo, intent: impl AsRef<str> + BamlEncode, ) -> (stream_types::ContractAnalysis, types::ContractAnalysis));


baml_function_sync!(AnalyzeEvent(contract_info: &types::ContractInfo, abi_result: &types::ABIAnalysisResult, intent: Option<impl AsRef<str> + BamlEncode>, ) -> (stream_types::EventAnalyzeResult, types::EventAnalyzeResult));


baml_function_sync!(AnalyzeLayout(contract_info: &types::ContractInfo, abi_result: &types::ABIAnalysisResult, intent: impl AsRef<str> + BamlEncode, ) -> (stream_types::LayoutAnalysisResult, types::LayoutAnalysisResult));


baml_function_sync!(ExtractContractInfo(group_operations: &[String], contracts: &[types::ContractInfo], ) -> (Vec<stream_types::ExtractedContractInfo>, Vec<types::ExtractedContractInfo>));


baml_function_sync!(ExtractResume(resume: impl AsRef<str> + BamlEncode, ) -> (stream_types::Resume, types::Resume));


baml_function_sync!(GenerateConversationSummary(messages: &[types::ChatMessage], ) -> (stream_types::ConversationSummary, types::ConversationSummary));


baml_function_sync!(GenerateScript(group_operations: &[String], extracted_infos: &[types::ExtractedContractInfo], ) -> (stream_types::ScriptBlock, types::ScriptBlock));


baml_function_sync!(GenerateTitle(messages: &[types::ChatMessage], ) -> (stream_types::SessionTitle, types::SessionTitle));


baml_function_sync!(GenerateTransactionCalls(operations: &[types::Operation], available_interfaces: &[types::InterfaceDefinition], deployed_addresses: &std::collections::HashMap<String, String>, ) -> (stream_types::GeneratedScript, types::GeneratedScript));


// =============================================================================
// Client Struct
// =============================================================================

#[derive(Clone)]
pub struct BamlSyncClient {
    options: FunctionOptions,
    
    pub AnalyzeABI: AnalyzeABI,
    
    pub AnalyzeContractForHandlers: AnalyzeContractForHandlers,
    
    pub AnalyzeEvent: AnalyzeEvent,
    
    pub AnalyzeLayout: AnalyzeLayout,
    
    pub ExtractContractInfo: ExtractContractInfo,
    
    pub ExtractResume: ExtractResume,
    
    pub GenerateConversationSummary: GenerateConversationSummary,
    
    pub GenerateScript: GenerateScript,
    
    pub GenerateTitle: GenerateTitle,
    
    pub GenerateTransactionCalls: GenerateTransactionCalls,
    
}

impl BamlSyncClient {
    pub const fn new() -> Self {
        Self {
            options: FunctionOptions::new(),
            
            AnalyzeABI: AnalyzeABI::new(),
            
            AnalyzeContractForHandlers: AnalyzeContractForHandlers::new(),
            
            AnalyzeEvent: AnalyzeEvent::new(),
            
            AnalyzeLayout: AnalyzeLayout::new(),
            
            ExtractContractInfo: ExtractContractInfo::new(),
            
            ExtractResume: ExtractResume::new(),
            
            GenerateConversationSummary: GenerateConversationSummary::new(),
            
            GenerateScript: GenerateScript::new(),
            
            GenerateTitle: GenerateTitle::new(),
            
            GenerateTransactionCalls: GenerateTransactionCalls::new(),
            
        }
    }

    /// Apply options to all functions. Returns a new client with the options set.
    pub fn with_options(&self, options: FunctionOptions) -> Self {
        Self {
            options: options.clone(),
            
            AnalyzeABI: AnalyzeABI { options: options.clone() },
            
            AnalyzeContractForHandlers: AnalyzeContractForHandlers { options: options.clone() },
            
            AnalyzeEvent: AnalyzeEvent { options: options.clone() },
            
            AnalyzeLayout: AnalyzeLayout { options: options.clone() },
            
            ExtractContractInfo: ExtractContractInfo { options: options.clone() },
            
            ExtractResume: ExtractResume { options: options.clone() },
            
            GenerateConversationSummary: GenerateConversationSummary { options: options.clone() },
            
            GenerateScript: GenerateScript { options: options.clone() },
            
            GenerateTitle: GenerateTitle { options: options.clone() },
            
            GenerateTransactionCalls: GenerateTransactionCalls { options: options.clone() },
            
        }
    }
}

// Builder convenience methods
impl_options_convenience_methods!(BamlSyncClient);

pub static B: BamlSyncClient = BamlSyncClient::new();