name: Deploy Backend (preview)

on:
  workflow_run:
    workflows:
      - Build and Push Docker Images
    types:
      - completed

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main' &&
      contains(join(github.event.workflow_run.pull_requests.*.merged, ','), 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend on preview host
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            set -euo pipefail
            cd /root/product-mono
            git fetch origin main
            git checkout main
            git pull --ff-only origin main
            ./scripts/compose-backend-prod.sh main
      - name: Verify backend health
        run: |
          set -euo pipefail
          response="$(curl -fsS https://api.staging.aomi.dev/health | tr -d '\r\n')"
          response="${response%%%}" # strip trailing %
          if [[ "$response" != "OK" ]]; then
            echo "Unexpected health response: $response"
            exit 1
          fi
